import { test, expect } from '@playwright/test';

/**
 * The body typeface is wired up in three places that have to agree:
 * `next/font` loads Manrope and names it `--font-body` (app/layout.tsx), the
 * root `<html>` carries the class that defines that variable, and `<body>`
 * carries the utility that spends it. Reading the source proves none of that -
 * a Tailwind arbitrary value whose type it cannot infer compiles to a rule for
 * the wrong property, emits no warning, and leaves the page in whatever the
 * browser picks for `ui-sans-serif`. `font-[var(--font-body)]` shipped for
 * exactly that reason: `font-` is both `font-family` and `font-weight`, and
 * Tailwind guessed weight, so the whole site rendered in the fallback face.
 *
 * So this asserts on the computed style in a real browser rather than on the
 * class list or the stylesheet text: the browser has already parsed the built
 * CSS and resolved the variable, which is the only place the mistake shows.
 * The family name is generated by `next/font` and carries a build hash
 * (`__Manrope_6b03d3`), so match the face, not the whole string.
 */
test.describe('Body typeface', () => {
  for (const path of ['/', '/coaches']) {
    test(`${path} renders in Manrope`, async ({ page }) => {
      await page.goto(path);
      await page.evaluate(() => document.fonts.ready);

      const fontFamily = await page.evaluate(() => getComputedStyle(document.body).fontFamily);

      expect(fontFamily).toMatch(/Manrope/i);
    });
  }
});
